INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 09:21:44] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 09:21:45] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 09:21:49] "[33mGET / HTTP/1.1[0m" 404 -
ERROR demo.py:6 error
DEBUG demo.py:7 debug
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 09:21:51] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 09:21:51] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 10:45:01] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 10:45:05] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 10:45:10] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 10:46:25] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 10:46:26] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 10:46:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO csrf.py:258 The CSRF token is missing.
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 11:26:22] "[31m[1mPOST /api/v1.0/post_data HTTP/1.1[0m" 400 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/__init__.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 11:26:39] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 12:03:03] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR index.py:30 (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'img_url' at row 1")
[SQL: INSERT INTO blog_articles (create_time, update_time, aid, title, author, content, img_url) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 2, 22, 15, 57, 28, 647536), datetime.datetime(2021, 2, 22, 15, 57, 28, 647546), 2, 'è¿™æ˜¯æ ‡é¢˜', 'è¿™æ˜¯ä½œè€…', 'è¿™æ˜¯æ–‡ç« å†…å®¹', 'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Fimg.daimg.com%2Fuploads%2Fallimg%2F140610%2F3-140610145414.jpg&refer=http%3A%2F%2Fimg.daimg.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1616572635&t=1f6bf7daf99c2fa20232b56b08f8f44f')]
(Background on this error at: http://sqlalche.me/e/13/9h9h)
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 15:57:28] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 15:58:50] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 16:40:54] "[35m[1mPOST /api/v1.0/post_data HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 16:41:57] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 16:44:22] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 16:44:26] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:29:02] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:29:02] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:29:05] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:29:08] "[33mGET /index HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:29:08] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:13] "[33mGET /index HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:30:44] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:31:29] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:31:29] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:31:29] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:31:29] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:31:29] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [22/Feb/2021 17:31:29] "[37mGET /api/v1.0/index?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:07:37] "[31m[1mPOST /api/v1.0/index HTTP/1.1[0m" 405 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:08:58] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/models.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:24:12] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:24:25] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:24:26] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:24:27] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:47:58] "[35m[1mGET /api/v1.0/index HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:48:23] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:50:40] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [23/Feb/2021 10:52:51] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:32:02] "[36mGET / HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:32:06] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:32:07] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:32:24] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:34:32] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:34:45] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:34:49] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:46] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:47] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:48] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:48] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:48] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:49] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:49] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:36:49] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:38:24] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:38:25] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:40:50] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:41:11] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:46:04] "[36mGET / HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:46:05] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:46:08] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:46:08] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:53:07] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:53:59] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:54:02] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:54:03] "[33mGET /api/v1.0/index HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:54:20] "[37mGET /api/v1.0/articles HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:54:20] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/web_html.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:54:40] "[37mGET /api/v1.0/articles HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:54:42] "[37mGET /api/v1.0/articles HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:56:14] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:56:17] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:56:18] "[33mGET /api/v1.0/index HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:56:25] "[33mGET /api/v1.0/index HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:56:27] "[37mGET /api/v1.0/articles HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/web_html.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:58:04] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 15:58:25] "[33mGET / HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/web_html.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:00:40] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:00:42] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:04:31] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:15:24] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:15:26] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:16:07] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:16:08] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:16:08] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:16:08] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:16:08] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:16:08] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:51:37] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:51:38] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:51:38] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:51:39] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 16:55:10] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:06:52] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:10:31] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:10:31] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:10:31] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:10:31] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:10:31] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
ERROR _internal.py:113 Error on request:
Traceback (most recent call last):
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/werkzeug/serving.py", line 315, in execute
    write(data)
  File "/Users/caoting/.virtualenvs/Flask_iHome/lib/python3.8/site-packages/werkzeug/serving.py", line 291, in write
    self.end_headers()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 529, in end_headers
    self.flush_headers()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/server.py", line 533, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socketserver.py", line 799, in write
    self._sock.sendall(b)
OSError: [Errno 41] Protocol wrong type for socket
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:10:31] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:15:38] "[37mPOST /api/v1.0/post_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:15:58] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:16:06] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:06] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:06] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:06] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:44] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:44] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:44] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:48] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:48] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:48] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:49] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:49] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:17:49] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:29:21] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:29:21] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:29:21] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:29:44] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:29:44] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:29:44] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:09] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:09] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:09] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:10] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:10] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:10] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:10] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:10] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:10] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:20] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:20] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:20] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:21] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:21] "[33mGET /blog/static/js/template.js HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [24/Feb/2021 17:30:21] "[33mGET /blog/static/js/index.js HTTP/1.1[0m" 404 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:13] "[36mGET / HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:14] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:14] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:20] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:20] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:20] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:20] "[37mGET /static/js/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:10:20] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:11:23] "[36mGET /demo.html HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:11:23] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:11:23] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:01] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:01] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:01] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:43] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:43] "[37mGET /static/js/template.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:43] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:43] "[37mGET /static/js/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:44] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:31:44] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:33:03] "[37mGET /demo.html HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:33:03] "[37mGET /api/v1.0/index HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [25/Feb/2021 09:33:03] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
ERROR __init__.py:98 Error: Directory migrations already exists and is not empty
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:34:56] "[37mGET /api/v1.0/get_list_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:37:22] "[37mGET /api/v1.0/get_list_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:38:07] "[31m[1mPOST /api/v1.0/revise_data HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:38:18] "[35m[1mPOST /api/v1.0/recise_data HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:38:49] "[37mPOST /api/v1.0/recise_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:40:09] "[31m[1mPOST /api/v1.0/get_list_data HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 16:40:15] "[37mGET /api/v1.0/get_list_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:15:25] "[37mPOST /api/v1.0/update_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:18:54] "[37mPOST /api/v1.0/update_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:28:06] "[37mPOST /api/v1.0/delete_data HTTP/1.1[0m" 200 -
ERROR index.py:135 (MySQLdb._exceptions.OperationalError) (1048, "Column 'aid' cannot be null")
[SQL: INSERT INTO blog_articles (create_time, update_time, aid, title, author, content, img_url, label) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 3, 2, 17, 29, 8, 133196), datetime.datetime(2021, 3, 2, 17, 29, 8, 133206), None, 'ä¿®æ”¹æ ‡é¢˜1', 'ä¿®æ”¹ä½œè€…1', 'ä¿®æ”¹æ–‡æœ¬1', 'http://127.0.0.1:5000/static/HOME/bedroome.jpeg', 'æ—…æ¸¸')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:29:08] "[37mPOST /api/v1.0/add_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR index.py:136 (MySQLdb._exceptions.OperationalError) (1366, "Incorrect integer value: 'aid' for column 'aid' at row 1")
[SQL: INSERT INTO blog_articles (create_time, update_time, aid, title, author, content, img_url, label) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 3, 2, 17, 30, 26, 309155), datetime.datetime(2021, 3, 2, 17, 30, 26, 309163), ['aid'], 'ä¿®æ”¹æ ‡é¢˜1', 'ä¿®æ”¹ä½œè€…1', 'ä¿®æ”¹æ–‡æœ¬1', 'http://127.0.0.1:5000/static/HOME/bedroome.jpeg', 'æ—…æ¸¸')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:30:26] "[37mPOST /api/v1.0/add_data HTTP/1.1[0m" 200 -
ERROR index.py:136 (MySQLdb._exceptions.OperationalError) (1366, "Incorrect integer value: 'aid' for column 'aid' at row 1")
[SQL: INSERT INTO blog_articles (create_time, update_time, aid, title, author, content, img_url, label) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 3, 2, 17, 30, 31, 338439), datetime.datetime(2021, 3, 2, 17, 30, 31, 338447), ['aid'], 'ä¿®æ”¹æ ‡é¢˜1', 'ä¿®æ”¹ä½œè€…1', 'ä¿®æ”¹æ–‡æœ¬1', 'http://127.0.0.1:5000/static/HOME/bedroome.jpeg', 'æ—…æ¸¸')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:30:31] "[37mPOST /api/v1.0/add_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
ERROR index.py:136 (MySQLdb._exceptions.OperationalError) (1366, "Incorrect integer value: 'aid' for column 'aid' at row 1")
[SQL: INSERT INTO blog_articles (create_time, update_time, aid, title, author, content, img_url, label) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: (datetime.datetime(2021, 3, 2, 17, 31, 45, 457387), datetime.datetime(2021, 3, 2, 17, 31, 45, 457395), ['aid'], 'ä¿®æ”¹æ ‡é¢˜1', 'ä¿®æ”¹ä½œè€…1', 'ä¿®æ”¹æ–‡æœ¬1', 'http://127.0.0.1:5000/static/HOME/bedroome.jpeg', 'æ—…æ¸¸')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:31:45] "[37mPOST /api/v1.0/add_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [02/Mar/2021 17:32:11] "[35m[1mPOST /api/v1.0/add_data HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 09:48:49] "[37mGET /api/v1.0/recise_data?aid=1 HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 09:48:56] "[33mGET /static/HOME/bedroome.jpeg HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 10:11:47] "[35m[1mGET /api/v1.0/recise_data HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 10:11:53] "[35m[1mGET /api/v1.0/recise_data HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 10:11:56] "[37mGET /api/v1.0/recise_data?aid=1 HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/models.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 15:53:23] "[35m[1mGET /api/v1.0/get_data HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 15:53:37] "[35m[1mGET /api/v1.0/get_data HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:22:11] "[35m[1mGET /api/v1.0/get_data HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:22:41] "[37mGET /api/v1.0/get_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/models.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:31:36] "[33mGET /api/v1.0/to_label_dict?lable=å±…å®¶ HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:31:58] "[33mGET /api/v1.0/to_label_dict?lable=%22å±…å®¶%22 HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:32:15] "[35m[1mGET /api/v1.0/get_label_data?lable=%22å±…å®¶%22 HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:32:20] "[35m[1mGET /api/v1.0/get_label_data?lable=å±…å®¶ HTTP/1.1[0m" 500 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:32:46] "[35m[1mGET /api/v1.0/get_label_data?label=å±…å®¶ HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:36:23] "[37mGET /api/v1.0/get_label_data?label=å±…å®¶ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:37:35] "[37mGET /api/v1.0/get_data HTTP/1.1[0m" 200 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/models.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:44:38] "[35m[1mGET /api/v1.0/get_detailed_data?aid=1&label=å±…å®¶ HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:47:18] "[35m[1mGET /api/v1.0/get_detailed_data?aid=1&label=å±…å®¶ HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:47:57] "[35m[1mGET /api/v1.0/get_detailed_data?aid=1&label=å±…å®¶ HTTP/1.1[0m" 500 -
INFO _internal.py:113  * Detected change in '/Users/caoting/PersonalBlog/blog/api_1_0/index.py', reloading
INFO _internal.py:113  * Restarting with stat
WARNING _internal.py:113  * Debugger is active!
INFO _internal.py:113  * Debugger PIN: 265-380-126
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 16:49:23] "[37mGET /api/v1.0/get_detailed_data?aid=1&label=å±…å®¶ HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:11:54] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:11:55] "[33mGET /%7B%7B%20art.img_url%20%7D%7D HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:11:55] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:15:23] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:15:23] "[31m[1mPOST /FeiEditor/traffic/log HTTP/1.1[0m" 405 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:04] "[37mGET / HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:04] "[37mGET /static/js/jquery.min.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:04] "[36mGET /static/js/template.js HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:04] "[37mGET /static/js/index.js HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:05] "[37mGET /api/v1.0/get_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:06] "[33mGET /static/HOME/bedroome.jpeg HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:17:42] "[33mGET /static/HOME/bedroome.jpeg HTTP/1.1[0m" 404 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:18:27] "[36mGET / HTTP/1.1[0m" 304 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:18:28] "[37mGET /api/v1.0/get_data HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:18:28] "[37mGET /favicon.ico HTTP/1.1[0m" 200 -
INFO _internal.py:113 127.0.0.1 - - [03/Mar/2021 17:18:29] "[37mGET /static/HOME/bedroom.jpeg HTTP/1.1[0m" 200 -
